-- Hash for 'password123' generated by werkzeug.security.generate_password_hash
-- (scrypt uses a random salt — this exact string only verifies 'password123')
SET @default_hash = 'scrypt:32768:8:1$HsFIevUMAvogns6I$8ba26431c1f64edbf9ac52f04ef3c1b881956e10e8983ed959f86a18077afc6035db11db80debd942e4bc9f01ac311b319175e87e6802118f7af8e30716c28db';

-- Insert Students (With accurate Eco Points for the High Score Board)
INSERT INTO Student (name, email, password_hash, student_number, acc_balance, eco_points) VALUES
('Son Gohan', 'gohan@campus.edu', @default_hash, '123000001', 39.70, 15),
('Aung Kyaw Zin', 'aung@campus.edu', @default_hash, 'CS2021001', 12.50, 28),
('Kyaw Zaw Htet', 'kyaw@campus.edu', @default_hash, 'CS2021002', 50.00, 20),
('Ye Min Aung', 'ye@campus.edu', @default_hash, 'CS2021003', 5.00, 8),
('Hnin Thida', 'hnin@campus.edu', @default_hash, 'CS2021004', 100.00, 5);

-- Insert Stores (Vendors)
INSERT INTO Store (name, email, password_hash, category, rating) VALUES
('Canteen A Bakery', 'bakery@campus.edu', @default_hash, 'Bakery', 4.30),
('Canteen B Chinese', 'chinese@campus.edu', @default_hash, 'Chinese', 4.10),
('Campus Cafe', 'cafe@campus.edu', @default_hash, 'Cafe', 4.40),
('Doragon Doru Sashimi', 'sushi@campus.edu', @default_hash, 'Japanese', 0.00);

-- Insert Blind Boxes (Some active, some hidden, different stocks)
INSERT INTO Blind_Box (store_ID, name, originalPrice, flashPrice, stockQuantity, is_active, pickUpDeadline) VALUES
(1, 'Sunrise Pastry Box', 12.00, 4.50, 2, TRUE, '19:30:00'),
(2, 'Surprise Bento', 15.00, 5.50, 3, TRUE, '21:00:00'),
(2, 'Noodle Combo Box', 13.00, 4.80, 1, TRUE, '20:30:00'),
(3, 'Cafe Snack Mystery', 9.00, 3.00, 1, TRUE, '18:00:00'),
(4, 'Sushi Boru', 50.00, 18.00, 12, TRUE, '21:00:00'),
(1, 'Stale Bread Bag', 5.00, 1.00, 0, FALSE, '15:00:00'); -- Hidden/Inactive box test case

-- Insert Orders (Simulating the state machine: Pending, Claimed, Canceled)
-- (SID 1 is Son Gohan, SID 2 is Aung Kyaw Zin)
INSERT INTO `Order` (SID, box_ID, status, pickup_code, order_timestamp) VALUES
(1, 2, 'Pending', '9F0B14', DATE_SUB(NOW(), INTERVAL 2 HOUR)),    -- Gohan's Pending Bento
(1, 3, 'Pending', '418320', DATE_SUB(NOW(), INTERVAL 1 HOUR)),    -- Gohan's Pending Noodles
(1, 2, 'Canceled', 'CANC3L', DATE_SUB(NOW(), INTERVAL 1 DAY)),    -- Gohan's Canceled Order (From screenshot)
(2, 1, 'Claimed', 'CLAIM1', DATE_SUB(NOW(), INTERVAL 2 DAY)),     -- Aung's Pastry (Ready for review)
(3, 4, 'Claimed', 'CLAIM2', DATE_SUB(NOW(), INTERVAL 3 DAY));     -- Kyaw's Cafe box

-- Insert Verified Reviews (Testing the 1:1 relation to Claimed Orders)
-- Order ID 4 (Aung's Pastry) and Order ID 5 (Kyaw's Cafe box)
INSERT INTO Review (order_ID, rating, comment) VALUES
(4, 5, 'Absolutely massive amount of croissants. Great value!'),
(5, 4, 'Sandwich was a bit squished but tasted amazing.');